@PORT = {{$dotenv PORT}}
@BASE_URL = http://localhost:{{PORT}}

### GetRemainingTodos
GET {{BASE_URL}}/todos

### NoteTodo
POST {{BASE_URL}}/note-todo
content-type: application/json

{
    "description": "Todo Item"
}

### MarkTodoAsDone
POST {{BASE_URL}}/mark-todo-as-done/ba1f45fe-cf17-4496-9e28-7a17d173acab
