// Contains a list of requests for testing purposes
// This file requires the VSCode Extension https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@base_url = http://localhost:3000

### GetRemainingTodos
GET {{base_url}}/todos

### NoteTodo
POST {{base_url}}/note-todo
content-type: application/json

{
    "description": "Todo Item"
}

### MarkTodoAsDone
POST {{base_url}}/mark-todo-as-done/ba1f45fe-cf17-4496-9e28-7a17d173acab
